---
- name: Download Items
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
  - { url: "https://www.python.org/ftp/python/2.7.8/python-2.7.8.msi", dest: "/home/ubuntu/python-2.7.8.msi" }
  - { url: "https://pypi.python.org/packages/source/P/PyInstaller/PyInstaller-2.1.zip", dest: "/home/ubuntu/pyinstaller.zip" }
  - { url: "http://downloads.sourceforge.net/project/pywin32/pywin32/Build%20217/pywin32-217.win32-py2.7.exe?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fpywin32%2Ffiles%2Fpywin32%2FBuild%2520217%2F&ts=1410031204&use_mirror=kent", dest: "/home/ubuntu/pywin32.exe" }
  - { url: "http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.1/PyQt4-4.11.1-gpl-Py2.7-Qt4.8.6-x32.exe?r=http%3A%2F%2Fwww.riverbankcomputing.co.uk%2Fsoftware%2Fpyqt%2Fdownload&ts=1410031650&use_mirror=skylink", dest: "/home/ubuntu/pyqt4.exe" }
  - { url: "http://prdownloads.sourceforge.net/nsis/nsis-2.46-setup.exe?download", dest: "/home/ubuntu/nsis.exe" }

- name: Initialize Environment
  shell: "{{ item }}"
  environment: en
  ignore_errors: true
  with_items:
  - "xvfb-run -a --server-num=4 wineboot"

- name: Unzip files
  shell: "{{ item }}"
  ignore_errors: true
  with_items:
  - "unzip /home/ubuntu/pyinstaller.zip"
  - "unzip /home/ubuntu/pywin32.exe"

- name: Install python
  shell: "{{ item }}"
  environment: en
  ignore_errors: true
  with_items:
  - "wine msiexec /i python-2.7.8.msi /qn TARGETDIR=c:\\\\Python27 ALLUSERS=1"

- name: pause
  pause: seconds=5

- name: Make dir
  file: path={{ item }} state=directory
  with_items:
  - "/home/ubuntu/.wine/drive_c/Python27/Lib/site-packages/"
  - "/home/ubuntu/.wine/drive_c/Python27/Scripts"

- name: Move file
  shell: "mv PyInstaller-2.1 $WINEPREFIX/drive_c/pyinstaller"
  environment: en

- name: Copy files
  shell: "cp -r {{ item.src }} {{ item.dest }}"
  with_items:
  - { src: "/home/ubuntu/PLATLIB/*", dest: "/home/ubuntu/.wine/drive_c/Python27/Lib/site-packages/" }
  - { src: "/home/ubuntu/SCRIPTS/*", dest: "/home/ubuntu/.wine/drive_c/Python27/Scripts/" }

- name: Python PostInstall
  shell: "{{ item }}"
  environment: en
  with_items:
  - "$PYTHON $PYHOME/Scripts/pywin32_postinstall.py -install"

- name: Install PyQt4
  command: "{{ item }}"
  environment: en
  with_items:
  - "xvfb-run -a wine pyqt4.exe /S"

- name: Install NSIS
  shell: "{{ item }}"
  environment: en
  with_items:
  - "xvfb-run -a wine nsis.exe /S"

